Implement fixed size grid with scalable cells and axis
BU-Spark/se-computerized-mapping-visual-fields pull request #2
Opened 2023-10-20 18:55 UTC by hanwj100

2023-10-20 23:22 UTC, zikunw requested changes
Great job! Just a little thing about tailwind and we should be able to merge it.

2023-10-20 23:22 UTC, zikunw commented on src/host/index.css
> +.grid {
blocking, style.
---
I see what you are doing here.
You could use tailwind in className where you name grid:
```javascript
className="flex justify-center items-center h-full"
```
which will give you the same thing. Unless we must, we try to avoid writing css.

2023-10-20 23:22 UTC, zikunw commented on src/host/App.tsx
> +        <Grid baseUnit={20} cellSize={1.5} />
Non-blocking, Style preference
---
Probably use a constant variable here instead of 20, something like:
```javascript
const BASE_UNIT = 20;
//...
<Grid baseUnit={BASE_UNIT} cellSize={1.5} />
```
Since during the meeting we discussed that this will not be an important factor.

2023-10-20 23:22 UTC, zikunw commented on src/host/App.tsx
> +      <div className="grid">
blocking.
---
`grid` is a class name that is already provided in tailwind. 
Also see the comment in the `src/host/index.css` file.

2023-10-22 19:04 UTC, braxton reviewed
LGTM after Zikun's commends are addressed

2023-10-24 13:21 UTC, hanwj100 commented on src/host/App.tsx
> +      <div className="grid">
Oh ok! I'm using tailwind utility classes now so it shouldn't conflict anymore.

2023-10-24 13:22 UTC, hanwj100 commented on src/host/index.css
> +.grid {
Got it, I'm familiarizing myself with tailwind and I've made the necessary adjustments!

2023-10-24 13:25 UTC, hanwj100 commented
I've addressed all the feedback and fixed the small bug for the scale drop down selection. Please take another look. Thanks!

2023-10-24 20:20 UTC, zikunw approved these changes
Looks good. 👍

2023-10-24 22:11 UTC, braxton commented
Let's hold off on merging this to make sure that #3 correctly blocks merging when files are not formatted properly

2023-10-24 22:11 UTC, braxton requested changes
Requesting changes to block

2023-10-24 23:01 UTC, braxton approved these changes

2023-10-27 20:28 UTC, merged